#=========================================================================
# Core Testbench
#=========================================================================

name: testbench

outputs:
  - testbench.sv
  - test_vectors.txt
  - design.args

parameters:
  testbench_name: CoreTb
  dut_name: core_inst

commands:
  - cp CoreTb.sv outputs/testbench.sv
  - python3 generate_test_vectors.py
  - cp test_vectors.txt outputs/test_vectors.txt
  - cp design.args outputs/design.args
