// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2024.2/1130128 Production Release
//  HLS Date:       Mon Aug 26 21:59:12 PDT 2024
// 
//  Generated by:   zsm9@zhang-21.ece.cornell.edu
//  Generated date: Fri Jul 31 15:02:56 2026
// ----------------------------------------------------------------------

// 
// ------------------------------------------------------------------
//  Design Unit:    hello_channel_comb
// ------------------------------------------------------------------


module hello_channel_comb (
  done, u0_done, u1_done
);
  output done;
  input u0_done;
  input u1_done;



  // Interconnect Declarations for Component Instantiations 
  assign done = u1_done & u0_done;
endmodule

// ------------------------------------------------------------------
//  Design Unit:    prod_0_run_run_fsm
//  FSM Module
// ------------------------------------------------------------------


module prod_0_run_run_fsm (
  clk, rst, fsm_output, v0_Pop_1_do_C_0_tr0, v1_Push_1_do_C_0_tr0, v1_Push_1_do_C_0_tr1
);
  input clk;
  input rst;
  output [3:0] fsm_output;
  reg [3:0] fsm_output;
  input v0_Pop_1_do_C_0_tr0;
  input v1_Push_1_do_C_0_tr0;
  input v1_Push_1_do_C_0_tr1;


  // FSM State Type Declaration for prod_0_run_run_fsm_1
  parameter
    run_rlp_C_0 = 2'd0,
    v0_Pop_1_do_C_0 = 2'd1,
    v1_Push_1_do_C_0 = 2'd2,
    while_C_0 = 2'd3;

  reg [1:0] state_var;
  reg [1:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : prod_0_run_run_fsm_1
    case (state_var)
      v0_Pop_1_do_C_0 : begin
        fsm_output = 4'b0010;
        if ( v0_Pop_1_do_C_0_tr0 ) begin
          state_var_NS = v0_Pop_1_do_C_0;
        end
        else begin
          state_var_NS = v1_Push_1_do_C_0;
        end
      end
      v1_Push_1_do_C_0 : begin
        fsm_output = 4'b0100;
        if ( v1_Push_1_do_C_0_tr0 ) begin
          state_var_NS = v0_Pop_1_do_C_0;
        end
        else if ( v1_Push_1_do_C_0_tr1 ) begin
          state_var_NS = v1_Push_1_do_C_0;
        end
        else begin
          state_var_NS = while_C_0;
        end
      end
      while_C_0 : begin
        fsm_output = 4'b1000;
        state_var_NS = while_C_0;
      end
      // run_rlp_C_0
      default : begin
        fsm_output = 4'b0001;
        state_var_NS = v0_Pop_1_do_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= run_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    cons_0_run_run_fsm
//  FSM Module
// ------------------------------------------------------------------


module cons_0_run_run_fsm (
  clk, rst, fsm_output, v5_Pop_1_do_C_0_tr0, v4_Push_1_do_C_0_tr0, v4_Push_1_do_C_0_tr1
);
  input clk;
  input rst;
  output [3:0] fsm_output;
  reg [3:0] fsm_output;
  input v5_Pop_1_do_C_0_tr0;
  input v4_Push_1_do_C_0_tr0;
  input v4_Push_1_do_C_0_tr1;


  // FSM State Type Declaration for cons_0_run_run_fsm_1
  parameter
    run_rlp_C_0 = 2'd0,
    v5_Pop_1_do_C_0 = 2'd1,
    v4_Push_1_do_C_0 = 2'd2,
    while_C_0 = 2'd3;

  reg [1:0] state_var;
  reg [1:0] state_var_NS;


  // Interconnect Declarations for Component Instantiations 
  always @(*)
  begin : cons_0_run_run_fsm_1
    case (state_var)
      v5_Pop_1_do_C_0 : begin
        fsm_output = 4'b0010;
        if ( v5_Pop_1_do_C_0_tr0 ) begin
          state_var_NS = v5_Pop_1_do_C_0;
        end
        else begin
          state_var_NS = v4_Push_1_do_C_0;
        end
      end
      v4_Push_1_do_C_0 : begin
        fsm_output = 4'b0100;
        if ( v4_Push_1_do_C_0_tr0 ) begin
          state_var_NS = v5_Pop_1_do_C_0;
        end
        else if ( v4_Push_1_do_C_0_tr1 ) begin
          state_var_NS = v4_Push_1_do_C_0;
        end
        else begin
          state_var_NS = while_C_0;
        end
      end
      while_C_0 : begin
        fsm_output = 4'b1000;
        state_var_NS = while_C_0;
      end
      // run_rlp_C_0
      default : begin
        fsm_output = 4'b0001;
        state_var_NS = v5_Pop_1_do_C_0;
      end
    endcase
  end

  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      state_var <= run_rlp_C_0;
    end
    else begin
      state_var <= state_var_NS;
    end
  end

endmodule

// ------------------------------------------------------------------
//  Design Unit:    prod_0_run
// ------------------------------------------------------------------


module prod_0_run (
  clk, rst, done, v0_vld, v0_rdy, v0_dat, v1_vld, v1_rdy, v1_dat
);
  input clk;
  input rst;
  output done;
  reg done;
  input v0_vld;
  output v0_rdy;
  reg v0_rdy;
  input [31:0] v0_dat;
  output v1_vld;
  reg v1_vld;
  input v1_rdy;
  output [31:0] v1_dat;
  reg [31:0] v1_dat;


  // Interconnect Declarations
  wire [3:0] fsm_output;
  wire [3:0] l_S_i_0_i_acc_1_tmp;
  wire [4:0] nl_l_S_i_0_i_acc_1_tmp;
  wire and_dcpl;
  wire nand_2_cse;
  wire v1_dat_and_cse;
  wire reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse;
  reg [2:0] l_S_i_0_i_i_3_0_sva_2_0;


  // Interconnect Declarations for Component Instantiations 
  wire  nl_prod_0_run_run_fsm_inst_v0_Pop_1_do_C_0_tr0;
  assign nl_prod_0_run_run_fsm_inst_v0_Pop_1_do_C_0_tr0 = ~ v0_vld;
  wire  nl_prod_0_run_run_fsm_inst_v1_Push_1_do_C_0_tr1;
  assign nl_prod_0_run_run_fsm_inst_v1_Push_1_do_C_0_tr1 = ~ v1_rdy;
  prod_0_run_run_fsm prod_0_run_run_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .v0_Pop_1_do_C_0_tr0(nl_prod_0_run_run_fsm_inst_v0_Pop_1_do_C_0_tr0),
      .v1_Push_1_do_C_0_tr0(and_dcpl),
      .v1_Push_1_do_C_0_tr1(nl_prod_0_run_run_fsm_inst_v1_Push_1_do_C_0_tr1)
    );
  assign v1_dat_and_cse = (fsm_output[1]) & v0_vld;
  assign nand_2_cse = ~(v1_rdy & (l_S_i_0_i_acc_1_tmp[3]));
  assign reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse = v1_rdy & (fsm_output[2]);
  assign nl_l_S_i_0_i_acc_1_tmp = conv_u2s_3_4(l_S_i_0_i_i_3_0_sva_2_0) + 4'b0001;
  assign l_S_i_0_i_acc_1_tmp = nl_l_S_i_0_i_acc_1_tmp[3:0];
  assign and_dcpl = v1_rdy & (~ (l_S_i_0_i_acc_1_tmp[3]));
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v1_dat <= 32'b00000000000000000000000000000000;
    end
    else if ( v1_dat_and_cse ) begin
      v1_dat <= v0_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v1_vld <= 1'b0;
    end
    else if ( v1_dat_and_cse | ((~ v1_rdy) & (fsm_output[2])) | reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse
        ) begin
      v1_vld <= ~ reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v0_rdy <= 1'b0;
    end
    else if ( ((~ v0_vld) & (fsm_output[1])) | (and_dcpl & (fsm_output[2])) | (fsm_output[0])
        | v1_dat_and_cse ) begin
      v0_rdy <= ~ v1_dat_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      done <= 1'b0;
    end
    else if ( ~((~ (fsm_output[2])) | nand_2_cse) ) begin
      done <= 1'b1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      l_S_i_0_i_i_3_0_sva_2_0 <= 3'b000;
    end
    else if ( reg_l_S_i_0_i_i_3_0_sva_2_l_S_i_0_i_i_l_S_i_0_i_i_and_cse & nand_2_cse
        ) begin
      l_S_i_0_i_i_3_0_sva_2_0 <= l_S_i_0_i_acc_1_tmp[2:0];
    end
  end

  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    cons_0_run
// ------------------------------------------------------------------


module cons_0_run (
  clk, rst, done, v4_vld, v4_rdy, v4_dat, v5_vld, v5_rdy, v5_dat
);
  input clk;
  input rst;
  output done;
  reg done;
  output v4_vld;
  reg v4_vld;
  input v4_rdy;
  output [31:0] v4_dat;
  reg [31:0] v4_dat;
  input v5_vld;
  output v5_rdy;
  reg v5_rdy;
  input [31:0] v5_dat;


  // Interconnect Declarations
  wire [3:0] fsm_output;
  wire [3:0] l_S_i_0_i1_acc_1_tmp;
  wire [4:0] nl_l_S_i_0_i1_acc_1_tmp;
  wire and_dcpl;
  wire nand_2_cse;
  wire v4_dat_and_cse;
  wire reg_l_S_i_0_i1_i1_3_0_sva_2_l_S_i_0_i1_i1_l_S_i_0_i1_i1_and_cse;
  reg [2:0] l_S_i_0_i1_i1_3_0_sva_2_0;


  // Interconnect Declarations for Component Instantiations 
  wire  nl_cons_0_run_run_fsm_inst_v5_Pop_1_do_C_0_tr0;
  assign nl_cons_0_run_run_fsm_inst_v5_Pop_1_do_C_0_tr0 = ~ v5_vld;
  wire  nl_cons_0_run_run_fsm_inst_v4_Push_1_do_C_0_tr1;
  assign nl_cons_0_run_run_fsm_inst_v4_Push_1_do_C_0_tr1 = ~ v4_rdy;
  cons_0_run_run_fsm cons_0_run_run_fsm_inst (
      .clk(clk),
      .rst(rst),
      .fsm_output(fsm_output),
      .v5_Pop_1_do_C_0_tr0(nl_cons_0_run_run_fsm_inst_v5_Pop_1_do_C_0_tr0),
      .v4_Push_1_do_C_0_tr0(and_dcpl),
      .v4_Push_1_do_C_0_tr1(nl_cons_0_run_run_fsm_inst_v4_Push_1_do_C_0_tr1)
    );
  assign v4_dat_and_cse = (fsm_output[1]) & v5_vld;
  assign nand_2_cse = ~(v4_rdy & (l_S_i_0_i1_acc_1_tmp[3]));
  assign reg_l_S_i_0_i1_i1_3_0_sva_2_l_S_i_0_i1_i1_l_S_i_0_i1_i1_and_cse = v4_rdy
      & (fsm_output[2]);
  assign nl_l_S_i_0_i1_acc_1_tmp = conv_u2s_3_4(l_S_i_0_i1_i1_3_0_sva_2_0) + 4'b0001;
  assign l_S_i_0_i1_acc_1_tmp = nl_l_S_i_0_i1_acc_1_tmp[3:0];
  assign and_dcpl = v4_rdy & (~ (l_S_i_0_i1_acc_1_tmp[3]));
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v5_rdy <= 1'b0;
    end
    else if ( ((~ v5_vld) & (fsm_output[1])) | (and_dcpl & (fsm_output[2])) | (fsm_output[0])
        | v4_dat_and_cse ) begin
      v5_rdy <= ~ v4_dat_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v4_dat <= 32'b00000000000000000000000000000000;
    end
    else if ( v4_dat_and_cse ) begin
      v4_dat <= v5_dat;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      v4_vld <= 1'b0;
    end
    else if ( v4_dat_and_cse | ((~ v4_rdy) & (fsm_output[2])) | reg_l_S_i_0_i1_i1_3_0_sva_2_l_S_i_0_i1_i1_l_S_i_0_i1_i1_and_cse
        ) begin
      v4_vld <= ~ reg_l_S_i_0_i1_i1_3_0_sva_2_l_S_i_0_i1_i1_l_S_i_0_i1_i1_and_cse;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      done <= 1'b0;
    end
    else if ( ~((~ (fsm_output[2])) | nand_2_cse) ) begin
      done <= 1'b1;
    end
  end
  always @(posedge clk or negedge rst) begin
    if ( ~ rst ) begin
      l_S_i_0_i1_i1_3_0_sva_2_0 <= 3'b000;
    end
    else if ( reg_l_S_i_0_i1_i1_3_0_sva_2_l_S_i_0_i1_i1_l_S_i_0_i1_i1_and_cse & nand_2_cse
        ) begin
      l_S_i_0_i1_i1_3_0_sva_2_0 <= l_S_i_0_i1_acc_1_tmp[2:0];
    end
  end

  function automatic [3:0] conv_u2s_3_4 ;
    input [2:0]  vector ;
  begin
    conv_u2s_3_4 =  {1'b0, vector};
  end
  endfunction

endmodule

// ------------------------------------------------------------------
//  Design Unit:    prod_0
// ------------------------------------------------------------------


module prod_0 (
  clk, rst, done, v0_vld, v0_rdy, v0_dat, v1_vld, v1_rdy, v1_dat
);
  input clk;
  input rst;
  output done;
  input v0_vld;
  output v0_rdy;
  input [31:0] v0_dat;
  output v1_vld;
  input v1_rdy;
  output [31:0] v1_dat;



  // Interconnect Declarations for Component Instantiations 
  prod_0_run prod_0_run_inst (
      .clk(clk),
      .rst(rst),
      .done(done),
      .v0_vld(v0_vld),
      .v0_rdy(v0_rdy),
      .v0_dat(v0_dat),
      .v1_vld(v1_vld),
      .v1_rdy(v1_rdy),
      .v1_dat(v1_dat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    cons_0
// ------------------------------------------------------------------


module cons_0 (
  clk, rst, done, v4_vld, v4_rdy, v4_dat, v5_vld, v5_rdy, v5_dat
);
  input clk;
  input rst;
  output done;
  output v4_vld;
  input v4_rdy;
  output [31:0] v4_dat;
  input v5_vld;
  output v5_rdy;
  input [31:0] v5_dat;



  // Interconnect Declarations for Component Instantiations 
  cons_0_run cons_0_run_inst (
      .clk(clk),
      .rst(rst),
      .done(done),
      .v4_vld(v4_vld),
      .v4_rdy(v4_rdy),
      .v4_dat(v4_dat),
      .v5_vld(v5_vld),
      .v5_rdy(v5_rdy),
      .v5_dat(v5_dat)
    );
endmodule

// ------------------------------------------------------------------
//  Design Unit:    hello_channel
// ------------------------------------------------------------------


module hello_channel (
  clk, rst, done, v8_vld, v8_rdy, v8_dat, v9_vld, v9_rdy, v9_dat
);
  input clk;
  input rst;
  output done;
  input v8_vld;
  output v8_rdy;
  input [31:0] v8_dat;
  output v9_vld;
  input v9_rdy;
  output [31:0] v9_dat;


  // Interconnect Declarations
  wire v10_vld;
  wire v10_rdy;
  wire [31:0] v10_dat;
  wire u0_done;
  wire u1_done;


  // Interconnect Declarations for Component Instantiations 
  prod_0 u0 (
      .clk(clk),
      .rst(rst),
      .done(u0_done),
      .v0_vld(v8_vld),
      .v0_rdy(v8_rdy),
      .v0_dat(v8_dat),
      .v1_vld(v10_vld),
      .v1_rdy(v10_rdy),
      .v1_dat(v10_dat)
    );
  cons_0 u1 (
      .clk(clk),
      .rst(rst),
      .done(u1_done),
      .v4_vld(v9_vld),
      .v4_rdy(v9_rdy),
      .v4_dat(v9_dat),
      .v5_vld(v10_vld),
      .v5_rdy(v10_rdy),
      .v5_dat(v10_dat)
    );
  hello_channel_comb hello_channel_comb_inst (
      .done(done),
      .u0_done(u0_done),
      .u1_done(u1_done)
    );
endmodule



